### ISSUE TITLE
Schulden sollen in raten zurückzahlbar sein

### ISSUE THREAD

**Issue by bdeenm** [DF0HSA/noodlz#2]
Bitte die Funktion einfügen das man Schulden in Raten zurückzahlen kann

**Comment by bdeenm** [comment]
Sehr gute idee

**Comment by bdeenm** [comment]
Эта функция была бы отличной

**Comment by tobyp** [comment]
Das passt überhaupt nicht in das aktuelle Modell, und würde mir die Software auch zu Bank-artig machen. Noodlz soll nur die Kommunikation/das Gedächtnis unterstützen, weil auf Messengern Nachrichten so schnell untergehen und vergessen werden.
