### ISSUE TITLE
Highlighting breaking out of box

### ISSUE THREAD

**Issue by firstdorsal** [DF0HSA/noodlz#4]
![signal-2020-02-03-172356](https://user-images.githubusercontent.com/10563452/73673732-75ee6400-46af-11ea-8624-9ced5244cedc.png)

Chrome 79
Win 10

**Comment by tobyp** [comment]
Thank you for the report! This turned out to be a problem on WebKit with box-shadows applying to the input element box, where Mozilla applies them to the checkbox.
